install_homebrew_if_missing: true

required_packages_brew:
  - zsh-autosuggestions
  - zsh-history-substring-search
  - helm

required_packages_apt:
  - stow
  - zsh
  - kitty
  - qemu-kvm
  - qemu-system 
  - qemu-utils 
  - libvirt-daemon 
  - virt-manager
  - pcscd
  - libpcsclite-dev
  - libfido2-1 
  - libfido2-dev 
  - libfido2-doc 
  - fido2-tools
  - pcsc-tools
  - libpam-yubico 
  - yubikey-personalization 
  - yubikey-manager
  - distrobox
  - unattended-upgrades
  - timeshift

#apt_keys:
#  - https://packages.microsoft.com/keys/microsoft.asc
#apt_repo:
#  - deb [arch=amd64] https://packages.microsoft.com/ubuntu/22.04/prod jammy main
#  - deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com noble main
#apt_repo_gpg:
#  - {name: "hashicorp-archive-keyring", url: "https://apt.releases.hashicorp.com/gpg"}

flatpak_remote:
  - {name: 'flathub', url: "https://dl.flathub.org/repo/flathub.flatpakrepo", method: "user"}

required_packages_flatpak:
  - me.proton.Mail
  - com.protonvpn.www
  - org.remmina.Remmina
  - com.github.tchx84.Flatseal
  - com.vscodium.codium
  - org.chromium.Chromium
  - com.parsecgaming.parsec
  - org.videolan.VLC
  - fr.handbrake.ghb
  - com.spotify.Client
  - org.signal.Signal
  - com.yubico.yubioath
  - io.gitlab.librewolf-community
  - com.brave.Browser

go_apps:
  - github.com/charmbracelet/vhs@latest
  - github.com/charmbracelet/glow@latest
  - github.com/swaggo/swag/cmd/swag@latest
  - github.com/air-verse/air@latest
  - github.com/minio/mc@latest

systemd_service:
  - libvirtd.service
  - pcscd.service
   
user_groups:
  - video
  - sudo
  - ykusers
